@extends('layouts.jquery')

@section('title', 'Customers - View Selected Customer Lead')

@push('css')
{{-- datetimepicker css --}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha512-PMjWzHVtwxdq7m7GIxBot5vdxUY+5aKP9wpKtvnNBZrVv1srI8tU6xvFMzG8crLNcMj/8Xl/WWmo/oAP/40p1g==" crossorigin="anonymous" />
{{-- datetimepicker css --}}
{{-- jquery datatables css --}}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap4.min.css">
{{-- jquery datatables css --}}
@endpush

@section('content')
<section>
  <div class="container py-5">

    {{-- title --}}
    <h3 class="text-secondary mb-0">CUSTOMERS</h3>
    <h5>View Selected Customer Lead</h5>
    {{-- title --}}

    {{-- navigation --}}
    <div class="row row-cols-1 row-cols-sm-4 pt-3">
      <div class="col pb-3">
        <a href="{{ route('leads.index') }}" class="btn btn-dark btn-block">
          <i class="fas fa-bars mr-2" aria-hidden="true"></i>Leads Menu
        </a>
      </div> {{-- col pb-3 --}}
      <div class="col pb-3">
        {{-- confirm modal --}}
        {{-- modal button --}}
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#confirmConvertModal">
          <i class="fas fa-user-cog mr-2" aria-hidden="true"></i>Convert Lead To Customer
        </button>
        {{-- modal button --}}
        {{-- modal --}}
        <div class="modal fade" id="confirmConvertModal" tabindex="-1" role="dialog" aria-labelledby="confirmConvertModalTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="confirmConvertModalTitle">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p class="text-center">Are you sure that you would like to convert this lead?</p>
                <form action="{{ route('convert-lead-to-customer.store') }}" method="POST">
                  @csrf
                  <input type="hidden" name="lead_id" value="{{ $lead->id }}">
                  <button type="submit" class="btn btn-primary btn-block">
                    <i class="fas fa-user-cog mr-2" aria-hidden="true"></i>Confirm
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {{-- modal --}}
        {{-- confirm modal --}}
      </div> {{-- col pb-3 --}}
      <div class="col pb-3">
        {{-- confirm modal --}}
        {{-- modal button --}}
        <button type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target="#confirmDeleteModal">
          <i class="fas fa-trash-alt mr-2" aria-hidden="true"></i>Delete
        </button>
        {{-- modal button --}}
        {{-- modal --}}
        <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalTitle">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p class="text-center">Are you sure that you would like to delete this lead?</p>
                <form action="{{ route('leads.destroy', $lead->id) }}" method="POST">
                    @method('DELETE')
                    @csrf
                  <button type="submit" class="btn btn-danger btn-block">
                    <i class="fas fa-trash-alt mr-2" aria-hidden="true"></i>Delete
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {{-- modal --}}
        {{-- confirm modal --}}
      </div> {{-- col pb-3 --}}
    </div> {{-- row row-cols-1 row-cols-sm-6 pt-3 --}}
    {{-- navigation --}}

    {{-- lead details --}}
    <div class="row">
      <div class="col-sm-8">

        <h5 class="text-primary my-3"><b>Lead Details</b></h5>
        <div class="table-responsive">
          <table class="table table-bordered table-fullwidth table-striped bg-white">
            <tbody>
              <tr>
                <th>Lead Generated By</th>
                <td>{{ $lead->staff->getFullNameAttribute() }}</td>
              </tr>
              <tr>
                <th>Date Created</th>
                <td>{{ date('d/m/y', strtotime($lead->created_at)) . ' - ' . $lead->created_at->diffForHumans() }}</td>
              </tr>
              <tr>
                <th>Contact Count</th>
                <td>
                  @if (!$lead->lead_contacts->count())
                    <span class="badge badge-light py-2 px-2">
                      <i class="fas fa-times mr-2" aria-hidden="true"></i>Customer has not been contacted
                    </span>
                  @else
                    {{ $lead->lead_contacts->count() }}
                  @endif
                </td>
              </tr>
              <tr>
                <th>Last Contact By</th>
                <td>
                  @if (!$lead->lead_contacts->count())
                    <span class="badge badge-light py-2 px-2">
                      <i class="fas fa-times mr-2" aria-hidden="true"></i>Customer has not been contacted
                    </span>
                  @else
                    {{ $lead->lead_contacts->last()->staff->getFullNameAttribute() }}
                  @endif
                </td>
              </tr>
              <tr>
                <th>Date Last Contacted</th>
                <td>
                  @if (!$lead->lead_contacts->count())
                    <span class="badge badge-light py-2 px-2">
                      <i class="fas fa-times mr-2" aria-hidden="true"></i>Customer has not been contacted
                    </span>
                  @else
                    {{ $lead->lead_contacts->last()->created_at->diffForHumans() }}
                  @endif
                </td>
              </tr>
            </tbody>          
          </table>
        </div> {{-- table-responsive --}}

      </div> {{-- col-sm-8 --}}
    </div> {{-- row --}}
    {{-- lead details --}}

  </div> {{-- container --}}
</section> {{-- section --}}
<section class="bg-white">
  <div class="container py-5">

    <div class="row">
      <div class="col-sm-8">

        <h5 class="text-primary my-3"><b>Customer Lead Details</b></h5>

        <form action="{{ route('leads.update', $lead->id) }}" method="POST">
          @method('PATCH')
          @csrf

          <div class="form-group row">
            <label for="email" class="col-md-3 col-form-label text-md-right">Name</label>
            <div class="col-md-4">
              <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror mb-2" name="first_name" value="{{ $lead->first_name }}" placeholder="Please enter the first name">
              @error('first_name')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-5 --}}
            <div class="col-md-4">
              <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror mb-2" name="last_name" value="{{ $lead->last_name }}" placeholder="Please enter the last name">
              @error('last_name')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-5 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="email" class="col-md-3 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
            <div class="col-md-8">
              <input id="email" type="email" class="form-control @error('email') is-invalid @enderror mb-2" name="email" value="{{ $lead->email }}" placeholder="Please enter the email">
              @error('email')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-6 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="street_address" class="col-md-3 col-form-label text-md-right">Street Address</label>
            <div class="col-md-8">
              <input id="street_address" type="text" class="form-control @error('street_address') is-invalid @enderror mb-2" name="street_address" value="{{ $lead->street_address }}" placeholder="Please enter the street address">
              @error('street_address')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-6 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="state" class="col-md-3 col-form-label text-md-right">State</label>
            <div class="col-md-8">
              <select name="state" id="state" class="custom-select @error('state') is-invalid @enderror mb-2">
                @if (old('state'))
                  <option disabled>Please select a state</option>
                  @foreach ($all_states as $state)
                    <option value="{{ $state->id }}" @if (old('state') == $state->id) selected @endif>{{ $state->title }}</option>
                  @endforeach
                @else
                  @if ($lead->state_id == null)
                    <option selected disabled>Please select a state</option>
                  @else
                    <option selected value="{{ $lead->state_id }}">{{ $lead->state->title }}</option>
                    <option disabled>Please select a state</option>
                    <option value=""></option>
                  @endif
                  @foreach ($all_states as $state)
                    <option value="{{ $state->id }}">{{ $state->title }}</option>
                  @endforeach
                @endif
              </select>
              @error('state')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-6 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="email" class="col-md-3 col-form-label text-md-right">Suburb</label>
            <div class="col-md-4">
              <input id="suburb" type="text" class="form-control @error('suburb') is-invalid @enderror mb-2" name="suburb" value="{{ $lead->suburb }}" placeholder="Please enter the suburb">
              @error('suburb')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-5 --}}
            <div class="col-md-4">
              <input id="postcode" type="text" class="form-control @error('postcode') is-invalid @enderror mb-2" name="postcode" value="{{ $lead->postcode }}" placeholder="Please enter the postcode">
              @error('postcode')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-5 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="home_phone" class="col-md-3 col-form-label text-md-right">Home Phone</label>
            <div class="col-md-8">
              <input id="home_phone" type="text" class="form-control @error('home_phone') is-invalid @enderror mb-2" name="home_phone" value="{{ $lead->home_phone }}" placeholder="Please enter the home phone">
              @error('home_phone')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="mobile_phone" class="col-md-3 col-form-label text-md-right">Mobile Phone</label>
            <div class="col-md-8">
              <input id="mobile_phone" type="text" class="form-control @error('mobile_phone') is-invalid @enderror mb-2" name="mobile_phone" value="{{ $lead->mobile_phone }}" placeholder="Please enter the mobile phone">
              @error('mobile_phone')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="account_class_id" class="col-md-3 col-form-label text-md-right">Account Class</label>
            <div class="col-md-8">
                <select name="account_class_id" id="account_class_id" class="custom-select @error('account_class_id') is-invalid @enderror mb-2">
                  @if (old('account_class_id'))
                    <option disabled>Please select an account class</option>
                    @foreach ($all_account_classes as $account_class)
                      <option value="{{ $account_class->id }}" @if (old('account_class_id') == $account_class->id) selected @endif>{{ $account_class->title }}</option>
                    @endforeach
                  @else
                    @if ($lead->account_class_id == null)
                      <option selected disabled>Please select a account class</option>
                    @else
                      <option selected value="{{ $lead->account_class_id }}">{{ $lead->account_class->title }}</option>
                      <option disabled>Please select an account class</option>
                    @endif
                    @foreach ($all_account_classes as $account_class)
                      <option value="{{ $account_class->id }}">{{ $account_class->title }}</option>
                    @endforeach
                  @endif
                </select>
                @error('account_class_id')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
            </div> {{-- col-md-6 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="referral" class="col-md-3 col-form-label text-md-right">Referral</label>
            <div class="col-md-8">
              <select name="referral" id="referral" class="custom-select @error('referral') is-invalid @enderror mb-2">
                @if (old('referral'))
                  <option disabled>Please select a referrer</option>
                  @foreach ($all_referrals as $referral)
                    <option value="{{ $referral->id }}" @if (old('referral') == $referral->id) selected @endif>{{ $referral->title }}</option>
                  @endforeach
                @else
                  @if ($lead->referral_id == null)
                    <option selected disabled>Please select a referral</option>
                  @else
                    <option selected value="{{ $lead->referral_id }}">{{ $lead->referral->title }}</option>
                    <option disabled>Please select a referral</option>
                    <option value=""></option>
                  @endif
                  @foreach ($all_referrals as $referral)
                    <option value="{{ $referral->id }}">{{ $referral->title }}</option>
                  @endforeach
                @endif
              </select>
              @error('referral')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-6 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="lead_status_id" class="col-md-3 col-form-label text-md-right">Lead Status</label>
            <div class="col-md-8">
              <select name="lead_status_id" id="lead_status_id" class="custom-select @error('lead_status_id') is-invalid @enderror mb-2">
                <option disabled>Please select a lead status</option>
                @foreach ($all_lead_statuses as $lead_status)
                    <option value="{{ $lead_status->id }}" @if (old('lead_status_id', $lead->lead_status->id) == $lead_status->id) selected @endif>{{ $lead_status->title }}</option>
                @endforeach
              </select>
              @error('lead_status_id')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-6 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="business_name" class="col-md-3 col-form-label text-md-right">Business Name</label>
            <div class="col-md-8">
              <input id="business_name" type="text" class="form-control @error('business_name') is-invalid @enderror mb-2" name="business_name" value="{{ $lead->business_name }}" placeholder="Please enter the business name">
              @error('business_name')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="abn" class="col-md-3 col-form-label text-md-right">ABN</label>
            <div class="col-md-8">
              <input id="abn" type="text" class="form-control @error('abn') is-invalid @enderror mb-2" name="abn" value="{{ $lead->abn }}" placeholder="Please enter the australian business number">
              @error('abn')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="business_phone" class="col-md-3 col-form-label text-md-right">Business Phone</label>
            <div class="col-md-8">
              <input id="business_phone" type="text" class="form-control @error('business_phone') is-invalid @enderror mb-2" name="business_phone" value="{{ $lead->business_phone }}" placeholder="Please enter the business phone">
              @error('business_phone')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="description" class="col-md-3 col-form-label text-md-right">Description</label>
            <div class="col-md-8">
              <textarea class="form-control @error('description') is-invalid @enderror mb-2" type="text" name="description" rows="10" placeholder="Please enter the description" style="resize:none">{{ $lead->description }}</textarea>
              @error('description')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row mb-0">
            <div class="col-md-8 offset-md-3">
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-edit mr-2" aria-hidden="true"></i>Edit
              </button>
              {{-- reset modal --}}
              {{-- modal button --}}
              <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#customerEditLeadModal">
                <i class="fas fa-undo-alt mr-2" aria-hidden="true"></i>Reset
              </button>
              {{-- modal button --}}
              {{-- modal --}}
              <div class="modal fade" id="customerEditLeadModal" tabindex="-1" role="dialog" aria-labelledby="customerEditLeadModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="customerEditLeadModalTitle">Reset</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p class="text-center">Are you sure that you would like to reset this form?</p>
                      <a href="{{ route('leads.show', $lead->id) }}" class="btn btn-dark btn-block">
                        <i class="fas fa-undo-alt mr-2" aria-hidden="true"></i>Reset
                      </a>
                    </div> {{-- modal-body --}}
                  </div> {{-- modal-content --}}
                </div> {{-- modal-dialog --}}
              </div> {{-- modal fade --}}
              {{-- modal --}}
              {{-- reset modal --}}
              <a href="{{ route('leads.index') }}" class="btn btn-dark">
                <i class="fas fa-times mr-2" aria-hidden="true"></i>Cancel
              </a>
            </div>
          </div>

        </form>

      </div> {{-- col-sm-8 --}}
    </div> {{-- row --}}

  </div> {{-- container --}}
</section> {{-- section --}}
<section>
  <div class="container py-5">

    <div class="row">
      <div class="col-sm-8">

        <h5 class="text-primary my-3"><b>New Lead Contact</b></h5>

        <form action="{{ route('lead-contacts.store') }}" method="POST">
          @csrf

          <input type="hidden" name="lead_id" value="{{ $lead->id }}">

          <div class="form-group row">
            <label for="title" class="col-md-2 col-form-label text-md-right">Call Back</label>
            <div class="col-md-9 mb-2">
              <div class="input-group date" id="call_back" data-target-input="nearest">
                <input type="text" name="call_back" class="form-control datetimepicker-input @error('call_back') is-invalid @enderror" data-target="#call_back" value="{{ old('call_back') }}" placeholder="Please enter the call back date and time"/>
                <div class="input-group-append" data-target="#call_back" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fas fa-calendar-alt"></i></div>
                </div>
                @error('call_back')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <div class="col-md-9 offset-md-2">
            <label class="checkbox">
              <input type="checkbox" name="call_back_date_null" {{ old('call_back_date_null') ? 'checked' : null }}>
              Unknown - (If the customer has not specified a call back date)
            </label>
            @error('call_back')
              <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
              </span>
            @enderror
            </div> {{-- col-md-9 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row">
            <label for="text" class="col-md-2 col-form-label text-md-right">Comment</label>
            <div class="col-md-9">
              <textarea class="form-control @error('comment') is-invalid @enderror mb-2" type="text" name="comment" rows="10" placeholder="Please enter the comment" style="resize:none">{{ $lead->comment }}</textarea>
              @error('comment')
                <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div> {{-- col-md-8 --}}
          </div> {{-- form-group row --}}

          <div class="form-group row mb-0">
            <div class="col-md-9 offset-md-2">
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-edit mr-2" aria-hidden="true"></i>Create
              </button>
              {{-- reset modal --}}
              {{-- modal button --}}
              <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#leadCommentModal">
                <i class="fas fa-undo-alt mr-2" aria-hidden="true"></i>Reset
              </button>
              {{-- modal button --}}
              {{-- modal --}}
              <div class="modal fade" id="leadCommentModal" tabindex="-1" role="dialog" aria-labelledby="leadCommentModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="leadCommentModalTitle">Reset</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p class="text-center">Are you sure that you would like to reset this form?</p>
                      <a href="{{ route('leads.show', $lead->id) }}" class="btn btn-dark btn-block">
                        <i class="fas fa-undo-alt mr-2" aria-hidden="true"></i>Reset
                      </a>
                    </div> {{-- modal-body --}}
                  </div> {{-- modal-content --}}
                </div> {{-- modal-dialog --}}
              </div> {{-- modal fade --}}
              {{-- modal --}}
              {{-- reset modal --}}
              <a href="{{ route('leads.index') }}" class="btn btn-dark">
                <i class="fas fa-times mr-2" aria-hidden="true"></i>Cancel
              </a>
            </div>
          </div>

        </form>

      </div> {{-- col-sm-8 --}}
    </div> {{-- row --}}

  </div> {{-- container --}}
</section> {{-- section --}}
<section class="bg-white">
  <div class="container py-5">

    <h5 class="text-primary my-3"><b>All Lead Contacts</b></h5>

    @if (!$lead_contacts->count())
      <div class="card shadow-sm mt-3">
          <div class="card-body text-center">
              <h5>Threre are no contacts to display</h5>
          </div> {{-- card-body --}}
      </div> {{-- card --}}
      @else
      <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered table-fullwidth bg-white" style="width:100%">
          <thead class="table-secondary">
            <tr>
              <th>Staff Name</th>
              <th>Contact Date</th>
              <th>Requested Call Back Date</th>
              <th>Comment</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($lead_contacts as $contact)
              <tr>
                <td>{{ $contact->staff->getFullNameAttribute() }}</td>
                <td>{{ date('d/m/y', strtotime($contact->created_at)) . ' - ' . $lead->created_at->diffForHumans() }}</td>
                <td>
                  @if ($contact->call_back_date == null)
                    <span class="badge badge-light py-2 px-2">
                      <i class="fas fa-times mr-2" aria-hidden="true"></i>A call back date has not been set
                    </span>
                  @else
                    {{ date('d/m/y - h:iA', strtotime($contact->call_back_date)) }}
                  @endif
                </td>
                <td>
                  {{ substr($contact->text, 0, 40) }}{{ strlen($contact->text) > 40 ? "..." : "" }}
                </td>
                <td class="text-center">
                  <a href="{{ route('lead-contacts.show', $contact->id) }}" class="btn btn-primary btn-sm">
                    <i class="fas fa-eye mr-2" aria-hidden="true"></i>View
                  </a>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div> {{-- table-responsive --}}
    @endif

  </div> {{-- container --}}
</section> {{-- section --}}
@endsection

@push('js')
{{-- Date Time Picker JS --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment.min.js" integrity="sha512-Q1f3TS3vSt1jQ8AwP2OuenztnLU6LwxgyyYOG1jgMW/cbEMHps/3wjvnl1P3WTrF3chJUWEoxDUEjMxDV8pujg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha512-2JBCbWoMJPH+Uj7Wq5OLub8E5edWHlTM4ar/YJkZh3plwB2INhhOC3eDoqHm1Za/ZOSksrLlURLoyXVdfQXqwg==" crossorigin="anonymous"></script>
<script type="text/javascript">
  $(function () {
    $('#call_back').datetimepicker({
      icons: {
        time: "fas fa-clock",
        date: "fas fa-calendar-alt",
        up: "fas fa-chevron-up",
        down: "fas fa-chevron-down"
      },
      format: 'DD-MM-YYYY LT',
    });
  });
</script>
{{-- Date Time Picker JS --}}
{{-- jquery datatables js --}}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap4.min.js"></script>
<script>
  $(document).ready(function() {
    $('#datatable').DataTable({
      "info": true, {{-- Show the page info --}}
      "lengthChange": true, {{-- Show results length --}}
      "ordering": true, {{-- Allow ordering of all columns --}}
      "paging": true, {{-- Show pagination --}}
      "processing": true, {{-- Show processing message on long load time --}}
      "searching": true, {{-- Search for results --}}
      order: [[ 1, "desc" ]],
      columnDefs: [
        {targets: 4, orderable: false, className: "text-center text-nowrap"},
      ],
    });
  });
</script>
{{-- jquery datatables js --}}
@endpush