<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateQuoteRequestsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('quote_requests', function (Blueprint $table) {
            // Primary key.
            $table->id();

            // Foreign keys.
            $table->foreignId('job_id')
                ->nullable()
                ->constrained('jobs')
                ->onUpdate('cascade')
                ->onDelete('cascade');

            $table->foreignId('quote_request_status_id')
                ->nullable()
                ->constrained('quote_request_statuses')
                ->onUpdate('cascade')
                ->onDelete('set null');

            $table->foreignId('staff_id')
                ->nullable()
                ->constrained('users')
                ->onUpdate('cascade')
                ->onDelete('set null');

            $table->foreignId('building_style_id')
                ->nullable()
                ->constrained('building_styles')
                ->onUpdate('cascade')
                ->onDelete('set null');

            // Potential customer details.
            $table->string('first_name'); // User First Name.
            $table->string('last_name'); // User Last Name.
            $table->string('username')->nullable(); // User Username.
            $table->string('email')->nullable(); // User Email.
            $table->string('home_phone')->nullable(); // User Contact Phone.
            $table->string('mobile_phone')->nullable(); // User Contact Phone.
            $table->string('street_address'); // User Street Address.
            $table->string('suburb'); // User Suburb.
            $table->string('postcode'); // User Postcode.

            // Building type.
            $table->boolean('house')->nullable(); // House.
            $table->boolean('carport')->nullable(); // Carport.
            $table->boolean('veranda')->nullable(); // Veranda.
            $table->boolean('pergola')->nullable(); // Pergola.
            $table->boolean('garage')->nullable(); // Garage.
            $table->boolean('garden_shed')->nullable(); // Garden Shed.
            $table->boolean('barn')->nullable(); // Barn.
            $table->boolean('retirement_village')->nullable(); // Retirement Village.
            $table->boolean('industrial_shed')->nullable(); // Industrial Shed.
            $table->boolean('house_unit')->nullable(); // House Unit.
            $table->boolean('school_buildings')->nullable(); // School Buildings.
            $table->boolean('church')->nullable(); // Church.
            $table->boolean('shops')->nullable(); // Shops.

            // Roof surfaces.
            $table->boolean('iron')->nullable(); // Iron - Colorbond.
            $table->boolean('slate')->nullable(); // Slate.
            $table->boolean('laserlight')->nullable(); // Laserlight.
            $table->boolean('cement')->nullable(); // Cement.
            $table->boolean('terracotta')->nullable(); // Terracotta.
            $table->boolean('paint')->nullable(); // Pre Painted.

            // Additions.
            $table->boolean('solar_panels')->nullable(); // Solor Panels.
            $table->boolean('air_conditioner')->nullable(); // Air Conditioner.
            $table->boolean('pool_heating')->nullable(); // Pool Heating.
            $table->boolean('under_aerial')->nullable(); // Under Aerial.
            $table->boolean('walls')->nullable(); // Walls.
            $table->boolean('additions_laserlight')->nullable(); // Laserlight.
            $table->boolean('outside_of_gutters')->nullable(); // Outside Of Gutters.
            $table->boolean('concrete_paths')->nullable(); // Concrete Paths.
            $table->text('additions_other')->nullable(); // Other input.

            // Others.
            $table->boolean('has_water_tanks')->default(0); // Has Water Tanks - radio button.
            $table->text('further_information')->nullable(); // Other Input.

            // Options.
            $table->boolean('is_customer_generated')->default(0); // Generated by Staff == 0, Generated by customer = 1.
            $table->boolean('is_editable')->default(1); // 0 = Not Editable / 1 = Editable.
            $table->boolean('is_delible')->default(1); // 0 = Not Delible / 1 = Delible.
            $table->boolean('is_latr')->default(0); // 0 = Normal / 1 = is from LATR.

            // Timestamps.
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('quote_requests');
    }
}
